### ISSUE TITLE
AttributeError: 'ImageData' object has no attribute 'data'

### ISSUE THREAD

**Issue by StevenIIV** [andywu0913/OpenAI-GYM-CarRacing-DQN#3]
when I run "python play_car_racing_with_keyboard.py", it freshed a window then closed, jump out this error
Env: macos big sur

 PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Track generation: 1165..1460 -> 295-tiles track
Traceback (most recent call last):
  File "play_car_racing_with_keyboard.py", line 91, in <module>
    state = env.reset()
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 49, in _reset
    return self.env.reset()
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 292, in _reset
    return self._step(None)[0]
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 304, in _step
    self.state = self._render("state_pixels")
  File "/Users/steveniiv/config/anaconda3/envs/DRL/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 380, in _render
    arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
AttributeError: 'ImageData' object has no attribute 'data'

**Comment by StevenIIV** [comment]
ok, I have fixed it by "pyglet == 1.3.2"
